### ISSUE TITLE
Gluster mount drive vs this plugin ?

### ISSUE THREAD

**Issue by iangregsondev** [trajano/docker-volume-plugins#38]
Hi,

Sorry for the silly question.

I have my gluster enabled on both my docker swarm machines. I basically write to /mnt/...... and gluster actually takes care of syncing the data.

What does this plugin allow me to do apart from that.

Yep, sorry, a silly question - I know :-)

But its not apparent to me what installing the plugin gives me when glusterfs takes care of the syncing anyway - is this not right ??

Anybody confirm?

Thanks

**Comment by trajano** [comment]
The original intent is so you don't install Gluster and all its dependencies on the OS level.  So your Docker nodes simply run docker.  However, since Docker swarm still does not support deployment of plugins via swarm up until now you'd still have to do this extra work manually.

When I originally wrote it I thought I can do the deployment through swarm but that wasn't the case.
